/**
 * API Conformance Suite — **transactions + audit writes** family (Phase 10c): the
 * write surface (`px.transaction(async tx => tx.<entity>.create / update /
 * terminate)`, spec §4.1) written as a developer would, run against each selected
 * provider through its shipped `@parallax/db-*` adapter, asserting the corpus's
 * `expectedTableState` (write sequences) or `expectRows` (read-your-own-writes).
 *
 * Writes are NOT read-shaped, so the `assertSameOperation` no-drift guard does not
 * apply; the guarantee is that the developer's write code leaves the DB in the
 * corpus's final state. The DML is generated by the pure M7 / M8 write generators
 * the runtime already owns (no reinvented DML, no grader code):
 *  - audit-only (Balance) create / update / terminate chain milestones (`m-audit-write-001`–`m-audit-write-003`),
 *    each transaction stamped with a fixed clock so the processing instants are the
 *    corpus's authored instants;
 *  - non-temporal batched writes flush set-based + FK-safe at commit (`m-batch-write-001` /
 *    `m-unit-work-003` / `m-batch-write-002`);
 *  - a dependent in-transaction find observes a buffered insert (`m-unit-work-001`);
 *  - a non-temporal timestamp insert stores UTC / µs precision (`m-core-002` / `m-core-003`).
 */

import { ParallaxDecimal, Temporal } from "@parallax/core";
import { afterAll, beforeAll, expect, describe as group, it } from "vitest";
import { AttributeExpression } from "../../src/index.js";
import {
  type ApiConformanceProvider,
  assertRows,
  assertTableState,
  provisionCase,
} from "./_harness.js";
import { HAS_DOCKER, writeProviders } from "./_providers.js";
import { TRANSACTIONS } from "./covered.js";

const attr = (ref: string): AttributeExpression => new AttributeExpression(ref);
const dec = (text: string): ParallaxDecimal => ParallaxDecimal.from(text);
const at = (iso: string): Temporal.Instant => Temporal.Instant.from(iso);

const Balance = { id: attr("Balance.id"), value: attr("Balance.value") };
const Account = { id: attr("Account.id"), balance: attr("Account.balance") };
const Wallet = { id: attr("Wallet.id"), balance: attr("Wallet.balance") };

it("the transactions suite covers exactly the TRANSACTIONS family", () => {
  const covered = [
    "m-core-002-timestamp-utc-normalization",
    "m-core-003-timestamp-microsecond-precision",
    "m-audit-write-001-insert",
    "m-audit-write-002-update-chaining",
    "m-audit-write-003-terminate",
    "m-batch-write-001-set-based-flush",
    "m-unit-work-001-read-your-own-writes",
    "m-unit-work-002-rollback-discards-writes",
    "m-unit-work-003-fk-insert-ordering",
    "m-batch-write-002-update-per-key",
  ];
  expect(covered.sort()).toEqual([...TRANSACTIONS].sort());
});

// Every transactions case drives the developer WRITE surface (create/update/terminate),
// so the family runs on every selected write-capable provider.
group.skipIf(!HAS_DOCKER).each(writeProviders())("transactions suite ($label)", (dbp) => {
  const BOOT_TIMEOUT = 600_000;
  let provider: ApiConformanceProvider;

  beforeAll(async () => {
    provider = await dbp.start();
  }, BOOT_TIMEOUT);

  afterAll(async () => {
    await provider?.close();
  });

  it(
    "m-core-002: a timestamp insert stores as UTC",
    async () => {
      const f = await provisionCase(provider, "m-core-002-timestamp-utc-normalization");
      await f.px.transaction(async (tx) => {
        await tx.entity("Event").create({ id: 1n, occurredAt: at("2024-03-01T05:30:00+05:30") });
      });
      await assertTableState(f);
    },
    BOOT_TIMEOUT,
  );

  it(
    "m-core-003: a timestamp insert keeps microsecond precision",
    async () => {
      const f = await provisionCase(provider, "m-core-003-timestamp-microsecond-precision");
      await f.px.transaction(async (tx) => {
        await tx
          .entity("Event")
          .create({ id: 1n, occurredAt: at("2024-03-01T12:00:00.123456+00:00") });
      });
      await assertTableState(f);
    },
    BOOT_TIMEOUT,
  );

  it(
    "m-audit-write-001: create opens an audit milestone [txInstant, infinity)",
    async () => {
      const f = await provisionCase(provider, "m-audit-write-001-insert", {
        now: "2024-01-01T00:00:00+00:00",
      });
      await f.px.transaction(async (tx) => {
        await tx.entity("Balance").create({ id: 1n, acctNum: "A", value: dec("100.00") });
      });
      await assertTableState(f);
    },
    BOOT_TIMEOUT,
  );

  it(
    "m-audit-write-002: update closes the current milestone and chains a new one (audit trail)",
    async () => {
      const f = await provisionCase(provider, "m-audit-write-002-update-chaining", {
        now: "2024-01-01T00:00:00+00:00",
      });
      // Milestone 1: open at 2024-01-01 (the first transaction's processing instant).
      await f.px.transaction(async (tx) => {
        await tx.entity("Balance").create({ id: 1n, acctNum: "A", value: dec("100.00") });
      });
      // A LATER transaction (a fresh clock at 2024-06-01) updates the balance: the
      // runtime closes the current row (out_z = 2024-06-01) and chains a new current
      // row carrying the new value — the prior value survives as a superseded milestone.
      const later = await withClock(f, "2024-06-01T00:00:00+00:00");
      await later.transaction(async (tx) => {
        await tx
          .entity("Balance")
          .update(Balance.id.eq(1), { set: [Balance.value.set(dec("150.00"))] });
      });
      await assertTableState(f);
    },
    BOOT_TIMEOUT,
  );

  it(
    "m-audit-write-003: terminate closes the current milestone and inserts nothing",
    async () => {
      const f = await provisionCase(provider, "m-audit-write-003-terminate", {
        now: "2024-01-01T00:00:00+00:00",
      });
      await f.px.transaction(async (tx) => {
        await tx.entity("Balance").create({ id: 1n, acctNum: "A", value: dec("100.00") });
      });
      const later = await withClock(f, "2024-08-01T00:00:00+00:00");
      await later.transaction(async (tx) => {
        await tx.entity("Balance").terminate(Balance.id.eq(1));
      });
      await assertTableState(f);
    },
    BOOT_TIMEOUT,
  );

  it(
    "m-batch-write-001: buffered inserts + updates flush as set-based SQL",
    async () => {
      const f = await provisionCase(provider, "m-batch-write-001-set-based-flush");
      await f.px.transaction(async (tx) => {
        const wallets = tx.entity("Wallet");
        await wallets.create({ id: 10n, owner: "Mira", balance: dec("100.00") });
        await wallets.create({ id: 11n, owner: "Omar", balance: dec("20.00") });
        await wallets.create({ id: 12n, owner: "Nell", balance: dec("30.00") });
        await wallets.update(Wallet.id.eq(10), { set: [Wallet.balance.set(dec("500.00"))] });
        await wallets.update(Wallet.id.eq(11), { set: [Wallet.balance.set(dec("500.00"))] });
      });
      await assertTableState(f);
    },
    BOOT_TIMEOUT,
  );

  it(
    "m-unit-work-001: a dependent find observes the buffered insert (read-your-own-writes)",
    async () => {
      const f = await provisionCase(provider, "m-unit-work-001-read-your-own-writes");
      const observed = await f.px.transaction(async (tx) => {
        const accounts = tx.entity("Account");
        await accounts.create({ id: 7n, owner: "Newton", balance: dec("5.00"), version: 1 });
        // The dependent find MUST observe the just-written row (a forced flush precedes it).
        return accounts.find(Account.id.eq(7)).toArray();
      });
      assertRows(observed, f.loaded, "Account", f.metamodel);
    },
    BOOT_TIMEOUT,
  );

  it(
    "m-unit-work-002: an aborted transaction discards its writes (rollback)",
    async () => {
      const f = await provisionCase(provider, "m-unit-work-002-rollback-discards-writes");
      const abort = new Error("abort the unit of work");
      // A write + a dependent find (forcing the RYOW flush), then a throw: the whole
      // unit of work maps onto ONE atomic scope, so the throw rolls the write back.
      await expect(
        f.px.transaction(async (tx) => {
          const accounts = tx.entity("Account");
          // Read account 1 first (records the observed version, M10), then update it.
          await accounts.find(Account.id.eq(1)).single();
          await accounts.update(Account.id.eq(1), { set: [Account.balance.set(dec("999.00"))] });
          const midTx = await accounts.find(Account.id.eq(1)).toArray();
          expect(midTx).toHaveLength(1);
          throw abort;
        }),
      ).rejects.toBe(abort);
      // After the abort, a fresh find re-resolves and MUST observe the ORIGINAL rows.
      const observed = await f.px.transaction(async (tx) =>
        tx.entity("Account").find(Account.id.eq(1)).toArray(),
      );
      assertRows(observed, f.loaded, "Account", f.metamodel);
    },
    BOOT_TIMEOUT,
  );

  it(
    "m-unit-work-003: a referenced parent is inserted before its child (FK ordering)",
    async () => {
      const f = await provisionCase(provider, "m-unit-work-003-fk-insert-ordering");
      await f.px.transaction(async (tx) => {
        await tx.entity("Order").create({
          id: 100n,
          name: "Hopper",
          sku: "X-1",
          qty: 1,
          price: dec("9.99"),
          active: true,
          orderedOn: Temporal.PlainDate.from("2024-07-01"),
        });
        await tx.entity("OrderItem").create({ id: 200n, orderId: 100n, sku: "X-1", quantity: 3 });
      });
      await assertTableState(f);
    },
    BOOT_TIMEOUT,
  );

  it(
    "m-batch-write-002: distinct new values flush as one keyed UPDATE per key",
    async () => {
      const f = await provisionCase(provider, "m-batch-write-002-update-per-key");
      await f.px.transaction(async (tx) => {
        const wallets = tx.entity("Wallet");
        await wallets.update(Wallet.id.eq(1), { set: [Wallet.balance.set(dec("111.00"))] });
        await wallets.update(Wallet.id.eq(2), { set: [Wallet.balance.set(dec("222.00"))] });
      });
      await assertTableState(f);
    },
    BOOT_TIMEOUT,
  );
});

/** Rebuild a `px` on the same provisioned DB with a fixed clock (a later transaction). */
async function withClock(
  fixture: Awaited<ReturnType<typeof provisionCase>>,
  now: string,
): Promise<import("../../src/index.js").Parallax> {
  const { createParallax } = await import("../../src/index.js");
  return createParallax({
    database: fixture.db,
    descriptor: fixture.loaded.descriptor,
    dialect: fixture.dialect,
    clock: { now: () => now },
  });
}
