/**
 * The `#parallax` barrel emitter (spec §2.1, §7).
 *
 * Renders the generated barrel source from the {@link CodegenModel}: one entity
 * symbol per entity (the value used in DSL expressions AND its `type` managed
 * object), the typed `parallax(...)` factory (`px`) with per-entity finders, and
 * the public runtime re-exports (`ParallaxList`, the error classes,
 * `ParallaxDecimal`, …). The output imports the runtime + DSL from
 * `@parallax/typescript` — legal because generated code lives in an application,
 * not a numbered package (no numbered package imports `@parallax/typescript`).
 *
 * Output is uncommitted / gitignored (ADR-0002); it is produced by `parallax
 * generate` and validated by `parallax generate --check`.
 */
import type {
  AttributeModel,
  CodegenModel,
  EntityModel,
  ToManyRelationshipModel,
  ToOneRelationshipModel,
  ValueObjectModel,
} from "./model.js";
import { usesDecimal, usesJson, usesTemporal, usesValueObjects } from "./model.js";

/** A single generated file: its output path (relative to `output`) and source. */
export interface GeneratedFile {
  readonly path: string;
  readonly contents: string;
}

/** The barrel's file name inside the output directory. */
export const BARREL_FILE = "index.ts" as const;

/** Escape a string for embedding as a double-quoted TypeScript string literal. */
function stringLiteral(value: string): string {
  return JSON.stringify(value);
}

/** The doc-comment banner every generated file carries. */
function banner(): string {
  return [
    "// AUTO-GENERATED by `parallax generate` — DO NOT EDIT.",
    "// Regenerate from the canonical descriptors; customization belongs in",
    "// descriptors, generator config, runtime adapters, and app-owned functions.",
    "// The physical output path is hidden behind the `#parallax` import alias.",
  ].join("\n");
}

/** The import block, conditioned on which runtime types the model needs. */
function imports(model: CodegenModel): string {
  const coreTypes: string[] = [];
  if (usesDecimal(model)) {
    coreTypes.push("ParallaxDecimal");
  }
  if (usesJson(model)) {
    coreTypes.push("ParallaxJsonValue");
  }
  const lines: string[] = [];
  const valueObjectImports = usesValueObjects(model)
    ? "  NestedFieldExpression,\n  ValueObjectExpression,\n"
    : "";
  lines.push(
    "import {\n" +
      "  AttributeExpression,\n" +
      "  createParallax,\n" +
      "  NavigationPath,\n" +
      "  Parallax,\n" +
      "  type ParallaxDatabase,\n" +
      "  type ParallaxOptions,\n" +
      "  type ParallaxRow,\n" +
      "  ParallaxTransaction,\n" +
      "  Predicate,\n" +
      "  ToManyRelationshipExpression,\n" +
      valueObjectImports +
      "  type FindOptions,\n" +
      "  type TransactionOptions,\n" +
      '} from "@parallax/typescript";',
  );
  // The public runtime types the barrel re-exports for applications (spec §2.1).
  const runtimeReexports = ["ParallaxList"];
  lines.push(`import { ${runtimeReexports.join(", ")} } from "@parallax/typescript";`);
  lines.push(
    "import {\n" +
      "  ParallaxError,\n" +
      "  ParallaxNotFoundError,\n" +
      "  ParallaxTooManyResultsError,\n" +
      '} from "@parallax/typescript";',
  );
  if (usesDecimal(model) || usesJson(model) || usesTemporal(model)) {
    const wanted = [...coreTypes];
    if (usesTemporal(model)) {
      wanted.push("Temporal");
    }
    lines.push(
      `import { ${wanted
        .sort()
        .map((t) => (t === "Temporal" ? "Temporal" : `type ${t}`))
        .join(", ")} } from "@parallax/typescript";`,
    );
  }
  return lines.join("\n");
}

/** Render one attribute's managed-object property (`id: bigint;`). */
function managedProperty(attr: AttributeModel): string {
  const type = attr.nullable ? `${attr.propertyType} | null` : attr.propertyType;
  return `  readonly ${attr.name}: ${type};`;
}

/** The managed-object property type for a value-object member (typed, arbitrary depth). */
function valueObjectPropertyType(vo: ValueObjectModel): string {
  if (vo.multiplicity === "many") {
    return `readonly ${vo.typeName}[]`;
  }
  return vo.nullable ? `${vo.typeName} | null` : vo.typeName;
}

/** Render one value object's managed property (`address: CustomerAddress | null;`). */
function valueObjectManagedProperty(vo: ValueObjectModel): string {
  return `  readonly ${vo.name}: ${valueObjectPropertyType(vo)};`;
}

/** Render the managed-object `type Entity = { … }` (scalar attributes + value objects). */
function managedType(entity: EntityModel): string {
  const props = [
    ...entity.attributes.map(managedProperty),
    ...entity.valueObjects.map(valueObjectManagedProperty),
  ].join("\n");
  return [
    `/** The managed \`${entity.name}\` domain object — its scalar attributes + value objects (spec §3.2.1). */`,
    `export type ${entity.name} = {`,
    props,
    "};",
  ].join("\n");
}

/**
 * Render the typed value-object interfaces for one value object and every member
 * nested inside it (recursive, arbitrary depth — m-value-object). Each is one
 * `type <Prefix><Name> = { … }` exposing the DECLARED members as typed getters: a
 * scalar field is its managed carrier (`| null` when nullable), a `one` nested
 * member is `Type | null`, a `many` member is `readonly Type[]`. There is NO
 * reverse getter and no relationship/lock/cache machinery — the composite rides
 * its owner (m-value-object "Materialization and navigation contract").
 */
function valueObjectInterfaces(vo: ValueObjectModel): readonly string[] {
  const members = [
    ...vo.fields.map(
      (f) => `  readonly ${f.name}: ${f.nullable ? `${f.propertyType} | null` : f.propertyType};`,
    ),
    ...vo.nested.map((child) => `  readonly ${child.name}: ${valueObjectPropertyType(child)};`),
  ].join("\n");
  const own = [
    `/** The typed \`${vo.name}\` value object — declared nested getters to arbitrary depth (m-value-object). */`,
    `export type ${vo.typeName} = {`,
    members,
    "};",
  ].join("\n");
  return [own, ...vo.nested.flatMap(valueObjectInterfaces)];
}

/** Every value-object interface an entity declares (top-level + nested, recursive). */
function entityValueObjectInterfaces(entity: EntityModel): string {
  return entity.valueObjects.flatMap(valueObjectInterfaces).join("\n\n");
}

/** Render one attribute symbol field (`id: new AttributeExpression("Order.id")`). */
function attributeSymbol(attr: AttributeModel): string {
  return `  ${attr.name}: new AttributeExpression(${stringLiteral(attr.ref)}),`;
}

/** Render one to-many relationship symbol field. */
function toManySymbol(rel: ToManyRelationshipModel): string {
  return `  ${rel.name}: new ToManyRelationshipExpression(${stringLiteral(rel.ref)}),`;
}

/** Render one to-one relationship include-path symbol field. */
function toOneSymbol(rel: ToOneRelationshipModel): string {
  return `  ${rel.name}: new NavigationPath([${stringLiteral(rel.ref)}]),`;
}

/** Indent every line of a block by two spaces. */
function indentBlock(block: string): string {
  return block
    .split("\n")
    .map((line) => (line.length > 0 ? `  ${line}` : line))
    .join("\n");
}

/**
 * Render the ELEMENT-relative predicate builder for a value object's scoped
 * `where` (`Customer.address.phones.element.type` → `nestedEq { path: "type" }`).
 * `prefix` is the element-relative path to this member from the `exists` root
 * (empty at the root), so a same-element compound uses element-relative paths.
 */
function elementBuilder(vo: ValueObjectModel, prefix: string): string {
  const rel = (name: string): string => (prefix === "" ? name : `${prefix}.${name}`);
  const members = [
    ...vo.fields.map((f) => `${f.name}: new NestedFieldExpression(${stringLiteral(rel(f.name))}),`),
    ...vo.nested.map((child) => `${child.name}: ${elementBuilder(child, rel(child.name))},`),
  ];
  return ["{", indentBlock(members.join("\n")), "}"].join("\n");
}

/**
 * Render the typed nested-predicate builder for one value object (m-value-object):
 * a `ValueObjectExpression` (carrying `exists` / `notExists` on the member) with
 * the declared typed accessors assigned onto it — a `NestedFieldExpression` per
 * scalar field (comparisons carrying the FULL dotted path), the recursive builder
 * per nested value object, and an `element` sub-builder exposing the same fields
 * on ELEMENT-relative paths for a scoped `where`. No reverse getter, no lock /
 * cache / statement machinery.
 */
function valueObjectBuilder(vo: ValueObjectModel): string {
  const members = [
    ...vo.fields.map((f) => `${f.name}: new NestedFieldExpression(${stringLiteral(f.ref)}),`),
    ...vo.nested.map((child) => `${child.name}: ${valueObjectBuilder(child)},`),
    `element: ${elementBuilder(vo, "")},`,
  ];
  return [
    `Object.assign(new ValueObjectExpression(${stringLiteral(vo.ref)}), {`,
    indentBlock(members.join("\n")),
    "})",
  ].join("\n");
}

/** Render one top-level value-object symbol field on the entity symbol. */
function valueObjectSymbol(vo: ValueObjectModel): string {
  return `  ${vo.name}: ${indentBlock(valueObjectBuilder(vo)).trimStart()},`;
}

/**
 * Render the entity symbol value (`export const Order = { … }`) — the RelatedFinder
 * analogue (spec §2.1). Carries the DSL attribute/relationship expressions, the
 * `all()` / `none()` identity predicates (spec §2.3), and the read metadata.
 *
 * The DSL attribute/relationship fields are authoritative: an attribute named
 * `table` (or a model whose attribute shadows the metadata key) wins, and the
 * colliding metadata field is dropped, so the symbol never emits a duplicate key
 * (the class name is always recoverable from the refs). This keeps the developer's
 * predicate surface intact whatever the descriptor names its columns.
 */
function entitySymbol(entity: EntityModel): string {
  const memberNames = new Set<string>([
    ...entity.attributes.map((a) => a.name),
    ...entity.toMany.map((r) => r.name),
    ...entity.toOne.map((r) => r.name),
    ...entity.valueObjects.map((vo) => vo.name),
    "all",
    "none",
  ]);
  const metadata: string[] = [];
  if (!memberNames.has("table")) {
    metadata.push(`  /** The mapped table name. */`, `  table: ${stringLiteral(entity.table)},`);
  }
  if (!memberNames.has("entityName")) {
    metadata.push(
      `  /** The domain class name (\`entityName\` to avoid colliding with a \`name\` attribute). */`,
      `  entityName: ${stringLiteral(entity.name)},`,
    );
  }
  const fields: string[] = [
    ...metadata,
    ...entity.attributes.map(attributeSymbol),
    ...entity.toMany.map(toManySymbol),
    ...entity.toOne.map(toOneSymbol),
    ...entity.valueObjects.map(valueObjectSymbol),
    `  /** The unfiltered identity predicate (\`find()\` shorthand, spec §2.3). */`,
    `  all(): Predicate {`,
    `    return new Predicate({ all: {} });`,
    `  },`,
    `  /** The empty predicate, for dynamic construction (spec §2.3). */`,
    `  none(): Predicate {`,
    `    return new Predicate({ none: {} });`,
    `  },`,
  ];
  return [
    `/** The \`${entity.name}\` entity symbol — DSL expression + metadata surface (spec §2.1). */`,
    `export const ${entity.name} = {`,
    fields.join("\n"),
    "} as const;",
  ].join("\n");
}

/** Render the typed handle interface (`Parallax` with per-entity finders). */
function handleType(model: CodegenModel): string {
  const finders = model.entities
    .map(
      (e) =>
        `  /** Finder for \`${e.name}\` — \`px.${e.finderName}.find(${e.name}.…)\`. */\n` +
        `  readonly ${e.finderName}: EntityFinder<${e.name}>;`,
    )
    .join("\n");
  return [
    "/** A typed entity finder — `find` returns a `ParallaxList` of managed objects. */",
    "export interface EntityFinder<T> {",
    "  find(predicate?: Predicate, options?: FindOptions): ParallaxList<T>;",
    "}",
    "",
    "/** The configured, typed Parallax handle (`px`, spec §2.2). */",
    "export interface TypedParallax {",
    finders,
    "  /** Closure-demarcated unit of work (spec §4); `options` selects the m-unit-work strategy. */",
    "  transaction<T>(",
    "    body: (tx: TypedParallaxTransaction) => Promise<T>,",
    "    options?: TransactionOptions,",
    "  ): Promise<T>;",
    "}",
    "",
    "/** The typed in-transaction handle (`tx`, spec §4). */",
    "export interface TypedParallaxTransaction {",
    model.entities.map((e) => `  readonly ${e.finderName}: EntityFinder<${e.name}>;`).join("\n"),
    "}",
  ].join("\n");
}

/**
 * Render the `parallax(...)` factory (spec §2.2). It bundles the descriptor,
 * delegates to the generic `createParallax`, and casts the entity-agnostic handle
 * to the typed shape — the generated finders are the same runtime `EntityFinder`,
 * typed to each entity's managed object.
 */
function factory(model: CodegenModel, descriptorJson: string): string {
  const finderAssignments = model.entities
    .map((e) => `    ${e.finderName}: base.entity<${e.name}>(${stringLiteral(e.name)}),`)
    .join("\n");
  const txFinderAssignments = model.entities
    .map((e) => `          ${e.finderName}: tx.entity<${e.name}>(${stringLiteral(e.name)}),`)
    .join("\n");
  return [
    "/** The bundled canonical descriptor the metamodel is read from (spec §7). */",
    `const DESCRIPTOR = ${descriptorJson} as const;`,
    "",
    "/** Options accepted by the generated `parallax(...)` factory. */",
    'export type ParallaxConfigOptions = Omit<ParallaxOptions, "descriptor">;',
    "",
    "/**",
    " * Create the configured, typed Parallax handle (`px`, spec §2.2). Binds the",
    " * bundled descriptor, database adapter, and clock; exposes typed per-entity",
    " * finders and the transaction demarcation.",
    " */",
    "export function parallax(options: ParallaxConfigOptions): TypedParallax {",
    "  const base: Parallax = createParallax({ ...options, descriptor: DESCRIPTOR });",
    "  return {",
    finderAssignments,
    "    transaction<T>(",
    "      body: (tx: TypedParallaxTransaction) => Promise<T>,",
    "      options?: TransactionOptions,",
    "    ): Promise<T> {",
    "      return base.transaction((tx: ParallaxTransaction) => {",
    "        const typed: TypedParallaxTransaction = {",
    txFinderAssignments,
    "        };",
    "        return body(typed);",
    "      }, options);",
    "    },",
    "  };",
    "}",
  ].join("\n");
}

/** The public runtime re-exports every barrel carries (spec §2.1). */
function reexports(): string {
  return [
    "// Public runtime types + error classes, re-exported for applications (spec §2.1).",
    "export {",
    "  ParallaxError,",
    "  ParallaxList,",
    "  ParallaxNotFoundError,",
    "  ParallaxTooManyResultsError,",
    "};",
    "export type { ParallaxDatabase, ParallaxRow, FindOptions, Predicate };",
  ].join("\n");
}

/**
 * Emit the whole `#parallax` barrel source for a model + its bundled descriptor
 * (serialized to embed in the output so the barrel is self-contained).
 */
export function emitBarrel(model: CodegenModel, descriptor: unknown): GeneratedFile {
  const descriptorJson = JSON.stringify(descriptor, null, 2);
  const valueObjectTypes = model.entities
    .filter((e) => e.valueObjects.length > 0)
    .map(entityValueObjectInterfaces);
  const sections = [
    banner(),
    imports(model),
    ...valueObjectTypes,
    ...model.entities.map(managedType),
    ...model.entities.map(entitySymbol),
    handleType(model),
    factory(model, descriptorJson),
    reexports(),
  ];
  return { path: BARREL_FILE, contents: `${sections.join("\n\n")}\n` };
}
