/**
 * The `#parallax` barrel emitter (spec §2.1, §7).
 *
 * Renders the generated barrel source from the {@link CodegenModel}: one entity
 * symbol per entity (the value used in DSL expressions AND its `type` managed
 * object), the typed `parallax(...)` factory (`px`) with per-entity finders, and
 * the public runtime re-exports (`ParallaxList`, the error classes,
 * `ParallaxDecimal`, …). The output imports the runtime + DSL from
 * `@parallax/typescript` — legal because generated code lives in an application,
 * not a numbered package (no numbered package imports `@parallax/typescript`).
 *
 * Output is uncommitted / gitignored (ADR-0003); it is produced by `parallax
 * generate` and validated by `parallax generate --check`.
 */
import type {
  AttributeModel,
  CodegenModel,
  EntityModel,
  ToManyRelationshipModel,
  ToOneRelationshipModel,
} from "./model.js";
import { usesDecimal, usesJson, usesTemporal } from "./model.js";

/** A single generated file: its output path (relative to `output`) and source. */
export interface GeneratedFile {
  readonly path: string;
  readonly contents: string;
}

/** The barrel's file name inside the output directory. */
export const BARREL_FILE = "index.ts" as const;

/** Escape a string for embedding as a double-quoted TypeScript string literal. */
function stringLiteral(value: string): string {
  return JSON.stringify(value);
}

/** The doc-comment banner every generated file carries. */
function banner(): string {
  return [
    "// AUTO-GENERATED by `parallax generate` — DO NOT EDIT.",
    "// Regenerate from the canonical descriptors; customization belongs in",
    "// descriptors, generator config, runtime adapters, and app-owned functions.",
    "// The physical output path is hidden behind the `#parallax` import alias.",
  ].join("\n");
}

/** The import block, conditioned on which runtime types the model needs. */
function imports(model: CodegenModel): string {
  const coreTypes: string[] = [];
  if (usesDecimal(model)) {
    coreTypes.push("ParallaxDecimal");
  }
  if (usesJson(model)) {
    coreTypes.push("ParallaxJsonValue");
  }
  const lines: string[] = [];
  lines.push(
    "import {\n" +
      "  AttributeExpression,\n" +
      "  createParallax,\n" +
      "  NavigationPath,\n" +
      "  Parallax,\n" +
      "  type ParallaxDatabase,\n" +
      "  type ParallaxOptions,\n" +
      "  type ParallaxRow,\n" +
      "  ParallaxTransaction,\n" +
      "  Predicate,\n" +
      "  ToManyRelationshipExpression,\n" +
      "  type FindOptions,\n" +
      "  type TransactionOptions,\n" +
      '} from "@parallax/typescript";',
  );
  // The public runtime types the barrel re-exports for applications (spec §2.1).
  const runtimeReexports = ["ParallaxList"];
  lines.push(`import { ${runtimeReexports.join(", ")} } from "@parallax/typescript";`);
  lines.push(
    "import {\n" +
      "  ParallaxError,\n" +
      "  ParallaxNotFoundError,\n" +
      "  ParallaxTooManyResultsError,\n" +
      '} from "@parallax/typescript";',
  );
  if (usesDecimal(model) || usesJson(model) || usesTemporal(model)) {
    const wanted = [...coreTypes];
    if (usesTemporal(model)) {
      wanted.push("Temporal");
    }
    lines.push(
      `import { ${wanted
        .sort()
        .map((t) => (t === "Temporal" ? "Temporal" : `type ${t}`))
        .join(", ")} } from "@parallax/typescript";`,
    );
  }
  return lines.join("\n");
}

/** Render one attribute's managed-object property (`id: bigint;`). */
function managedProperty(attr: AttributeModel): string {
  const type = attr.nullable ? `${attr.propertyType} | null` : attr.propertyType;
  return `  readonly ${attr.name}: ${type};`;
}

/** Render the managed-object `type Entity = { … }`. */
function managedType(entity: EntityModel): string {
  const props = entity.attributes.map(managedProperty).join("\n");
  return [
    `/** The managed \`${entity.name}\` domain object — its scalar attributes (spec §3.2.1). */`,
    `export type ${entity.name} = {`,
    props,
    "};",
  ].join("\n");
}

/** Render one attribute symbol field (`id: new AttributeExpression("Order.id")`). */
function attributeSymbol(attr: AttributeModel): string {
  return `  ${attr.name}: new AttributeExpression(${stringLiteral(attr.ref)}),`;
}

/** Render one to-many relationship symbol field. */
function toManySymbol(rel: ToManyRelationshipModel): string {
  return `  ${rel.name}: new ToManyRelationshipExpression(${stringLiteral(rel.ref)}),`;
}

/** Render one to-one relationship include-path symbol field. */
function toOneSymbol(rel: ToOneRelationshipModel): string {
  return `  ${rel.name}: new NavigationPath([${stringLiteral(rel.ref)}]),`;
}

/**
 * Render the entity symbol value (`export const Order = { … }`) — the RelatedFinder
 * analogue (spec §2.1). Carries the DSL attribute/relationship expressions, the
 * `all()` / `none()` identity predicates (spec §2.3), and the read metadata.
 *
 * The DSL attribute/relationship fields are authoritative: an attribute named
 * `table` (or a model whose attribute shadows the metadata key) wins, and the
 * colliding metadata field is dropped, so the symbol never emits a duplicate key
 * (the class name is always recoverable from the refs). This keeps the developer's
 * predicate surface intact whatever the descriptor names its columns.
 */
function entitySymbol(entity: EntityModel): string {
  const memberNames = new Set<string>([
    ...entity.attributes.map((a) => a.name),
    ...entity.toMany.map((r) => r.name),
    ...entity.toOne.map((r) => r.name),
    "all",
    "none",
  ]);
  const metadata: string[] = [];
  if (!memberNames.has("table")) {
    metadata.push(`  /** The mapped table name. */`, `  table: ${stringLiteral(entity.table)},`);
  }
  if (!memberNames.has("entityName")) {
    metadata.push(
      `  /** The domain class name (\`entityName\` to avoid colliding with a \`name\` attribute). */`,
      `  entityName: ${stringLiteral(entity.name)},`,
    );
  }
  const fields: string[] = [
    ...metadata,
    ...entity.attributes.map(attributeSymbol),
    ...entity.toMany.map(toManySymbol),
    ...entity.toOne.map(toOneSymbol),
    `  /** The unfiltered identity predicate (\`find()\` shorthand, spec §2.3). */`,
    `  all(): Predicate {`,
    `    return new Predicate({ all: {} });`,
    `  },`,
    `  /** The empty predicate, for dynamic construction (spec §2.3). */`,
    `  none(): Predicate {`,
    `    return new Predicate({ none: {} });`,
    `  },`,
  ];
  return [
    `/** The \`${entity.name}\` entity symbol — DSL expression + metadata surface (spec §2.1). */`,
    `export const ${entity.name} = {`,
    fields.join("\n"),
    "} as const;",
  ].join("\n");
}

/** Render the typed handle interface (`Parallax` with per-entity finders). */
function handleType(model: CodegenModel): string {
  const finders = model.entities
    .map(
      (e) =>
        `  /** Finder for \`${e.name}\` — \`px.${e.finderName}.find(${e.name}.…)\`. */\n` +
        `  readonly ${e.finderName}: EntityFinder<${e.name}>;`,
    )
    .join("\n");
  return [
    "/** A typed entity finder — `find` returns a `ParallaxList` of managed objects. */",
    "export interface EntityFinder<T> {",
    "  find(predicate?: Predicate, options?: FindOptions): ParallaxList<T>;",
    "}",
    "",
    "/** The configured, typed Parallax handle (`px`, spec §2.2). */",
    "export interface TypedParallax {",
    finders,
    "  /** Closure-demarcated unit of work (spec §4); `options` selects the m-unit-work strategy. */",
    "  transaction<T>(",
    "    body: (tx: TypedParallaxTransaction) => Promise<T>,",
    "    options?: TransactionOptions,",
    "  ): Promise<T>;",
    "}",
    "",
    "/** The typed in-transaction handle (`tx`, spec §4). */",
    "export interface TypedParallaxTransaction {",
    model.entities.map((e) => `  readonly ${e.finderName}: EntityFinder<${e.name}>;`).join("\n"),
    "}",
  ].join("\n");
}

/**
 * Render the `parallax(...)` factory (spec §2.2). It bundles the descriptor,
 * delegates to the generic `createParallax`, and casts the entity-agnostic handle
 * to the typed shape — the generated finders are the same runtime `EntityFinder`,
 * typed to each entity's managed object.
 */
function factory(model: CodegenModel, descriptorJson: string): string {
  const finderAssignments = model.entities
    .map((e) => `    ${e.finderName}: base.entity<${e.name}>(${stringLiteral(e.name)}),`)
    .join("\n");
  const txFinderAssignments = model.entities
    .map((e) => `          ${e.finderName}: tx.entity<${e.name}>(${stringLiteral(e.name)}),`)
    .join("\n");
  return [
    "/** The bundled canonical descriptor the metamodel is read from (spec §7). */",
    `const DESCRIPTOR = ${descriptorJson} as const;`,
    "",
    "/** Options accepted by the generated `parallax(...)` factory. */",
    'export type ParallaxConfigOptions = Omit<ParallaxOptions, "descriptor">;',
    "",
    "/**",
    " * Create the configured, typed Parallax handle (`px`, spec §2.2). Binds the",
    " * bundled descriptor, database adapter, and clock; exposes typed per-entity",
    " * finders and the transaction demarcation.",
    " */",
    "export function parallax(options: ParallaxConfigOptions): TypedParallax {",
    "  const base: Parallax = createParallax({ ...options, descriptor: DESCRIPTOR });",
    "  return {",
    finderAssignments,
    "    transaction<T>(",
    "      body: (tx: TypedParallaxTransaction) => Promise<T>,",
    "      options?: TransactionOptions,",
    "    ): Promise<T> {",
    "      return base.transaction((tx: ParallaxTransaction) => {",
    "        const typed: TypedParallaxTransaction = {",
    txFinderAssignments,
    "        };",
    "        return body(typed);",
    "      }, options);",
    "    },",
    "  };",
    "}",
  ].join("\n");
}

/** The public runtime re-exports every barrel carries (spec §2.1). */
function reexports(): string {
  return [
    "// Public runtime types + error classes, re-exported for applications (spec §2.1).",
    "export {",
    "  ParallaxError,",
    "  ParallaxList,",
    "  ParallaxNotFoundError,",
    "  ParallaxTooManyResultsError,",
    "};",
    "export type { ParallaxDatabase, ParallaxRow, FindOptions, Predicate };",
  ].join("\n");
}

/**
 * Emit the whole `#parallax` barrel source for a model + its bundled descriptor
 * (serialized to embed in the output so the barrel is self-contained).
 */
export function emitBarrel(model: CodegenModel, descriptor: unknown): GeneratedFile {
  const descriptorJson = JSON.stringify(descriptor, null, 2);
  const sections = [
    banner(),
    imports(model),
    ...model.entities.map(managedType),
    ...model.entities.map(entitySymbol),
    handleType(model),
    factory(model, descriptorJson),
    reexports(),
  ];
  return { path: BARREL_FILE, contents: `${sections.join("\n\n")}\n` };
}
